# This file is part of convertdate.
# http://github.com/fitnr/convertdate
# Licensed under the MIT license:
# http://opensource.org/licenses/MIT
# Copyright (c) 2016-2020, fitnr <fitnr@fakeisthenewreal>
os: linux
arch:
  - amd64
  - ppc64le

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - pypy3

matrix:
  exclude:
    - arch: ppc64le
      python: pypy3

# Use container-based infrastructure
sudo: false

install:
  - pip install tox-travis

script:
  - tox
